# Generated by Django 4.2.11 on 2024-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='collage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
