# Generated by Django 4.2.11 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_studentprofile_collage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_year',
            field=models.PositiveIntegerField(blank=True, help_text='Format: YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('6', 'Sixth Year'), ('7', 'Seventh Year')], default='1', max_length=1),
        ),
    ]
