# Generated by Django 4.2.11 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_studentprofile_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='average',
            field=models.FloatField(default=0.0, help_text='Average grade'),
        ),
    ]
