# Generated by Django 4.2.11 on 2024-04-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
        ('Users', '0006_alter_studentprofile_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Loans.loan'),
        ),
    ]
