# Generated by Django 4.2.11 on 2024-04-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0003_alter_loan_amount_alter_loan_approved_date_and_more'),
        ('Users', '0007_studentprofile_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Loans.loan'),
        ),
    ]
