# Generated by Django 4.2.11 on 2024-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_studentprofile_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=850, max_digits=10),
        ),
    ]
