# Generated by Django 4.2.11 on 2024-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
