# Generated by Django 4.2.11 on 2024-05-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
