# Generated by Django 4.2.11 on 2024-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
