# Generated by Django 4.2.11 on 2024-05-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_user_active_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
