# Generated by Django 4.2.11 on 2024-04-14 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConsultanciesServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancybooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultancybooking',
            name='consulting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bookings', to='ConsultanciesServices.consulting'),
        ),
    ]
