# Generated by Django 4.2.11 on 2024-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultanciesServices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancybooking',
            name='consulting',
        ),
        migrations.AddField(
            model_name='consultancybooking',
            name='booked_for',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Consulting',
        ),
    ]
