# Generated by Django 4.2.11 on 2024-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultanciesServices', '0004_remove_consultancybooking_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('specialization', models.CharField(max_length=64)),
                ('experience', models.IntegerField()),
                ('description', models.TextField(max_length=256)),
                ('profile_picture', models.ImageField(upload_to='consultants/profile_pictures/')),
            ],
        ),
    ]
