# Generated by Django 4.2.11 on 2024-05-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultanciesServices', '0005_consulting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancybooking',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='consultancybooking',
            name='booked_for',
        ),
        migrations.RemoveField(
            model_name='consultancybooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consultancybooking',
            name='time',
        ),
    ]
