# Generated by Django 4.2.11 on 2024-05-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConsultanciesServices', '0006_remove_consultancybooking_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancybooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultancybooking',
            name='booked_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bookings', to='ConsultanciesServices.consulting'),
        ),
        migrations.AddField(
            model_name='consultancybooking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancybooking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
