# Generated by Django 4.2.11 on 2024-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultanciesServices', '0007_consultancybooking_booked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='specialization',
            field=models.IntegerField(),
        ),
    ]
