# Generated by Django 4.2.11 on 2024-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0003_alter_loan_amount_alter_loan_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='apply_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
