# Generated by Django 4.2.11 on 2024-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0005_remove_loan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='months_paid',
            field=models.IntegerField(default=0),
        ),
    ]
