# Generated by Django 4.2.11 on 2024-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0006_loan_months_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
