# Generated by Django 4.2.11 on 2024-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mark', models.CharField(choices=[('AP', 'Apple'), ('HW', 'Huawei'), ('AD', 'Android')], max_length=2)),
                ('category', models.CharField(choices=[('SP', 'Smart Phone'), ('TL', 'Tablet & Laptop'), ('AC', 'Accessories')], max_length=2)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='Suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailsField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='Products.product')),
            ],
        ),
    ]
