# Generated by Django 4.2.11 on 2024-04-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mark',
            new_name='brand',
        ),
    ]
