# Generated by Django 4.2.11 on 2024-04-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
        ('Products', '0005_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='delivery_charge',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(auto_created=True, db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='Suppliers.supplier'),
        ),
    ]
