# Generated by Django 4.2.11 on 2024-04-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_bill_delivery_charge_alter_bill_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='supplier',
        ),
    ]
