# Generated by Django 4.2.11 on 2024-04-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_bill_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adderss',
            field=models.TextField(blank=True, null=True),
        ),
    ]
