# Generated by Django 4.2.11 on 2024-04-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_rename_adderss_order_adders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adders',
            new_name='address',
        ),
    ]
